"""Kafka topic registry for the MAS inter-agent communication bus.

All inter-agent communication passes through Apache Kafka topics.
Agents never call each other directly via HTTP/RPC.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Topic:
    """A Kafka topic definition with metadata."""

    name: str
    description: str
    partitions: int = 6
    retention_hours: int = 168  # 7 days default
    schema_class: str = ""
    """Name of the Pydantic message class used for this topic."""


# ── Complete Topic Registry ──────────────────────────────────────────
# All topics are defined here to serve as the single source of truth.

TOPIC_REGISTRY: dict[str, Topic] = {
    # ── Task Lifecycle ───────────────────────────────────────────────
    "task.assigned": Topic(
        name="task.assigned",
        description="CEO Orchestrator or Vertical Manager assigns a task to an agent.",
        schema_class="TaskAssignedMessage",
    ),
    "task.completed": Topic(
        name="task.completed",
        description="An agent reports task completion to its upstream coordinator.",
        schema_class="TaskCompletedMessage",
    ),
    "task.failed": Topic(
        name="task.failed",
        description="An agent reports task failure.",
        schema_class="TaskFailedMessage",
    ),

    # ── Deliverable Pipeline ─────────────────────────────────────────
    "deliverable.ready": Topic(
        name="deliverable.ready",
        description="An agent submits a deliverable for QA validation.",
        schema_class="DeliverableReadyMessage",
    ),
    "deliverable.approved": Topic(
        name="deliverable.approved",
        description="QA Agent approves a deliverable for client delivery.",
        schema_class="DeliverableApprovedMessage",
    ),
    "deliverable.rejected": Topic(
        name="deliverable.rejected",
        description="QA Agent rejects a deliverable (sent back for revision).",
        schema_class="DeliverableRejectedMessage",
    ),

    # ── Client Health ────────────────────────────────────────────────
    "client.health.alert": Topic(
        name="client.health.alert",
        description="Ops Agent raises alert when Client Health Score drops below 65.",
        schema_class="ClientHealthAlertMessage",
    ),

    # ── Regulatory & Knowledge ───────────────────────────────────────
    "regulatory.update.healthcare": Topic(
        name="regulatory.update.healthcare",
        description="Healthcare regulatory change detected.",
        schema_class="RegulatoryUpdateMessage",
    ),
    "regulatory.update.logistics": Topic(
        name="regulatory.update.logistics",
        description="Logistics regulatory change detected.",
        schema_class="RegulatoryUpdateMessage",
    ),
    "regulatory.update.legal": Topic(
        name="regulatory.update.legal",
        description="Legal regulatory change detected (primary supersession source).",
        schema_class="RegulatoryUpdateMessage",
    ),
    "regulatory.update.edtech": Topic(
        name="regulatory.update.edtech",
        description="EdTech regulatory or syllabus change detected.",
        schema_class="RegulatoryUpdateMessage",
    ),
    "kb.supersession": Topic(
        name="kb.supersession",
        description="A KB document has been superseded by a newer version.",
        schema_class="KBSupersessionMessage",
        retention_hours=720,  # 30 days
    ),

    # ── MAS Health & Oversight ───────────────────────────────────────
    "mas.health.report": Topic(
        name="mas.health.report",
        description="Weekly MAS Health Report generated by CEO Orchestrator.",
        schema_class="MASHealthReportMessage",
        retention_hours=2160,  # 90 days
    ),
    "escalation.required": Topic(
        name="escalation.required",
        description="An agent requires human oversight approval.",
        schema_class="EscalationMessage",
    ),

    # ── Tender Pipeline ──────────────────────────────────────────────
    "tender.new": Topic(
        name="tender.new",
        description="New government tender detected by the Tender Bidding Agent.",
        schema_class="TenderNewMessage",
    ),
    "tender.bid.generated": Topic(
        name="tender.bid.generated",
        description="Bid package generated, awaiting human approval.",
        schema_class="TenderBidMessage",
    ),

    # ── Affiliate & Revenue ──────────────────────────────────────────
    "affiliate.event": Topic(
        name="affiliate.event",
        description="Affiliate marketing event (click, conversion, payout).",
        schema_class="AffiliateEventMessage",
    ),

    # ── Market Intelligence ──────────────────────────────────────────
    "market.intelligence.digest": Topic(
        name="market.intelligence.digest",
        description="Weekly market intelligence digest.",
        schema_class="MarketIntelDigestMessage",
        retention_hours=2160,  # 90 days
    ),

    # ── Audit ────────────────────────────────────────────────────────
    "audit.log": Topic(
        name="audit.log",
        description="Every agent action is logged for compliance and traceability.",
        schema_class="AuditLogMessage",
        partitions=12,
        retention_hours=8760,  # 365 days
    ),
}
