name: Deploy Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
        working-directory: infra/terraform
      - name: Terraform Apply
        run: terraform apply -var-file="environments/production.tfvars" -auto-approve
        working-directory: infra/terraform
        env:
          TF_VAR_redpanda_client_id: ${{ secrets.REDPANDA_CLIENT_ID }}
          TF_VAR_redpanda_client_secret: ${{ secrets.REDPANDA_CLIENT_SECRET }}
          TF_VAR_upstash_email: ${{ secrets.UPSTASH_EMAIL }}
          TF_VAR_upstash_api_key: ${{ secrets.UPSTASH_API_KEY }}
          TF_VAR_supabase_access_token: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          TF_VAR_supabase_organization_id: ${{ secrets.SUPABASE_ORGANIZATION_ID }}
